# Ejercicio 16: DataFrame de estudiantes

**Enunciado:** crear un DataFrame con 10 estudiantes que incluya nombre, carrera, edad, promedio y ciudad.

**Lógica:** se utiliza pandas para crear una tabla de estudiantes. Luego se muestran las primeras filas, la información general, el promedio general, los estudiantes con promedio mayor o igual a 80 y finalmente se ordenan de mayor a menor promedio.

In [2]:
import pandas as pd

datos = {
    "Nombre": ["Ana", "Luis", "Carlos", "María", "José", "Sofía", "Pedro", "Lucía", "Juan", "Gabriela"],
    "Carrera": ["Sistemas", "Derecho", "Medicina", "Sistemas", "Administración", "Psicología", "Civil", "Arquitectura", "Contaduría", "Industrial"],
    "Edad": [20, 21, 22, 19, 23, 20, 24, 22, 21, 20],
    "Promedio": [85, 78, 90, 82, 75, 95, 70, 88, 80, 92],
    "Ciudad": ["Tegucigalpa", "Comayagua", "La Ceiba", "Danlí", "Choluteca", "SPS", "Juticalpa", "Siguatepeque", "Tela", "Tegucigalpa"]
}

df = pd.DataFrame(datos)

print("Primeras 5 filas:")
display(df.head())

print("Información general:")
df.info()

promedio_general = df["Promedio"].mean()
print(f"\nPromedio general: {promedio_general:.2f}")

print("\nEstudiantes con promedio mayor o igual a 80:")
display(df[df["Promedio"] >= 80])

print("\nEstudiantes ordenados de mayor a menor promedio:")
display(df.sort_values(by="Promedio", ascending=False))

Primeras 5 filas:

   Nombre         Carrera  Edad  Promedio       Ciudad
0     Ana        Sistemas    20        85  Tegucigalpa
1    Luis         Derecho    21        78    Comayagua
2  Carlos        Medicina    22        90     La Ceiba
3   María        Sistemas    19        82        Danlí
4    José  Administración    23        75    Choluteca

Información general:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nombre    10 non-null     str
 1   Carrera   10 non-null     str
 2   Edad      10 non-null     int64
 3   Promedio  10 non-null     int64
 4   Ciudad    10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

Promedio general: 83.50

Estudiantes con promedio mayor o igual a 80:

     Nombre       Carrera  Edad  Promedio        Ciudad
0       Ana      Sistemas    20        85   Tegucigalpa
2    Carlos      Medicina    22        90      La Ceiba
3     María      Sistemas    19        82         Danlí
5     Sofía    Psicología    20        95           SPS
7     Lucía  Arquitectura    22        88  Siguatepeque
8      Juan    Contaduría    21        80          Tela
9  Gabriela    Industrial    20        92   Tegucigalpa

Estudiantes ordenados de mayor a menor promedio:

     Nombre         Carrera  Edad  Promedio        Ciudad
5     Sofía      Psicología    20        95           SPS
9  Gabriela      Industrial    20        92   Tegucigalpa
2    Carlos        Medicina    22        90      La Ceiba
7     Lucía    Arquitectura    22        88  Siguatepeque
0       Ana        Sistemas    20        85   Tegucigalpa
3     María        Sistemas    19        82         Danlí
8      Juan      Contaduría    21        80          Tela
1      Luis         Derecho    21        78     Comayagua
4      José  Administración    23        75     Choluteca
6     Pedro           Civil    24        70     Juticalpa